MODEL (
  name SAMPLE_DATASET.DP_DATASETS.CUSTOMER,
  kind FULL,
  grains (CUSTOMER_NUMBER),
  description 'Customer data from the Snowflake Sample Dataset',
  owner 'abhishekbharadwajtmdcio',
  tags ('customers', 'finance'),
  column_descriptions (
    CUSTOMER_NUMBER = 'Unique customer identifier.',
    CUSTOMER_NAME = 'Customer name.',
    CUSTOMER_ADDRESS = 'Customer address.',
    CUSTOMER_NATIONKEY = 'Nation key for the customer.',
    CUSTOMER_PHONE = 'Customer phone number.',
    CUSTOMER_ACCOUNT_BALANCE = 'Account balance for the customer.',
    CUSTOMER_MARKET_SEGMENT = 'Market segment for the customer.',
    CUSTOMER_COMMENT = 'Free-text comment on the customer.'
  ),
  columns (
    CUSTOMER_NUMBER INTEGER,
    CUSTOMER_NAME VARCHAR,
    CUSTOMER_ADDRESS VARCHAR,
    CUSTOMER_NATIONKEY INTEGER,
    CUSTOMER_PHONE VARCHAR,
    CUSTOMER_ACCOUNT_BALANCE DECIMAL(18, 2),
    CUSTOMER_MARKET_SEGMENT VARCHAR,
    CUSTOMER_COMMENT VARCHAR
  )
);

WITH customers AS (
  SELECT
    C_CUSTKEY AS CUSTOMER_NUMBER,
    C_NAME AS CUSTOMER_NAME,
    C_ADDRESS AS CUSTOMER_ADDRESS,
    C_NATIONKEY AS CUSTOMER_NATIONKEY,
    C_PHONE AS CUSTOMER_PHONE,
    C_ACCTBAL AS CUSTOMER_ACCOUNT_BALANCE,
    C_MKTSEGMENT AS CUSTOMER_MARKET_SEGMENT,
    C_COMMENT AS CUSTOMER_COMMENT
  FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
)
SELECT
  CUSTOMER_NUMBER,
  CUSTOMER_NAME,
  CUSTOMER_ADDRESS,
  CUSTOMER_NATIONKEY,
  CUSTOMER_PHONE,
  CUSTOMER_ACCOUNT_BALANCE,
  CUSTOMER_MARKET_SEGMENT,
  CUSTOMER_COMMENT
FROM customers
