connection:
  type: snowflake
  account: zbjtkef-qo50193
  user: "{{ env_var('SNOWFLAKE_USER') }}"
  password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
  warehouse: COMPUTE_WH
  database: SAMPLE_DATASET
  role: ACCOUNTADMIN
